sudo: false
language: python
python: '2.7'

before_install:
  - echo -e "machine github.com\n  login ${GH_TOKEN}" >> ~/.netrc

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install https://github.com/bmcorser/fontawesome-markdown/archive/master.zip

script:
  - mkdocs build

after_success:
  - git config user.name "Andre Roussakoff"
  - git config user.email "madrus@gmail.com"
  - git remote add gh-token "https://${GH_TOKEN}@github.com/madrus/kdocs.git";
  - git fetch gh-token gh-pages:gh-pages;
  - mkdocs gh-deploy --clean --remote-name gh-token;
