sudo: false
language: python
python: '2.7'

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install https://github.com/bmcorser/fontawesome-markdown/archive/master.zip

script:
  - mkdocs build

after_success:
  - mkdocs gh-deploy
