# Project information
site_name: "Madrus's Docs"
site_description: 'A short description of my project'
site_author: 'Madrus'
site_url: 'https://madrus.github.io/kdocs'
site_favicon: 'images/favicon.ico'

# Repository
#repo_name: 'GitHub'  # will it work with GitLab?
repo_url: 'https://github.com/madrus/kdocs'

# Pages structure
pages:
  - Home: index.md
  - MkDocs:
    - Technicalities: mkdocs/technicalities.md
    - Custom Styling: mkdocs/custom_styling.md
  - Umbraco:
    - Technicalities: umbraco/technicalities.md
  - Vue.js:
    - Basics: vuejs/basics.md
  - Playground:
    - TODOs: playground/todo.md
    - Test Document: playground/test.md

# Documentation and theme
docs_dir: 'docs'
theme: readthedocs
theme_dir: custom_theme
# theme: cerulean
# theme: flatly
# theme: slate
# theme: cinder
# theme: alabaster
# theme: bootstrap
extra_css: [css/extra.css]
extra_javascript: []

# Options
extra:
  version: 0.1.0
  logo: 'images/logo.png'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(css_class=code):
      guess_lang: false
  - fontawesome_markdown
  - nl2br
  - smarty:
      smart_angled_quotes: true
  - toc:
      permalink: '#'

#Copyright
copyright: Copyright &copy; 2016 <a href="https://madrus4u.com">Balans4U</a>

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'
