# Project information
site_name: "Madrus's Docs"
site_description: 'A short description of my project'
site_author: 'Madrus'
site_url: 'https://madrus.github.io/kdocs'
site_favicon: 'images/favicon.ico'

# Repository
#repo_name: 'GitHub'  # will it work with GitLab?
repo_url: 'https://github.com/madrus/kdocs'

# Pages structure
pages:
  - Home: index.md
  - MkDocs:
    - Technicalities: mkdocs/technicalities.md
    - Custom Styling: mkdocs/custom_styling.md
  - Umbraco:
    - Technicalities: umbraco/technicalities.md
  - Sandbox:
    - TODOs: sandbox/todo.md
    - Test Document: sandbox/test.md

# Documentation and theme
docs_dir: 'docs'
theme: readthedocs
# theme: cerulean
# theme: flatly
# theme: slate
# theme: cinder
# theme: alabaster
# theme: bootstrap

# Options
extra:
  logo: 'images/logo.png'

markdown_extensions:
  - admonition
  - codehilite(css_class=code):
      guess_lang: false
  - nl2br
  - smarty:
      smart_angled_quotes: true
  - toc:
      permalink: '#'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'
